// export const config = {
//   labels: [],
//   datasets: [
//     {
//       label: '',
//       data: [],
//       borderColor: 'rgb(0, 130, 158)',
//       borderDashOffset: 0.0,
//       pointBorderColor: 'rgb(205, 130,1 58)',
//       pointBorderWidth: 3,
//       pointHoverRadius: 5,
//       pointHoverBackgroundColor: 'rgb(0, 0, 0)',
//       pointHoverBorderWidth: 2,
//       pointRadius: 1,
//       pointHitRadius: 10,
//       trendlineLinear: {
//         colorMin: 'black',
//         colorMax: 'black',
//         width: 1,
//       },
//     },
//     {
//       label: 'Sandviksgatan 54',
//       data: [],
//       borderColor: 'rgb(0, 130, 158)',
//       borderDashOffset: 0.0,
//       pointBorderColor: 'rgb(205, 130,1 58)',
//       pointBorderWidth: 3,
//       pointHoverRadius: 5,
//       pointHoverBackgroundColor: 'rgb(0, 0, 0)',
//       pointHoverBorderWidth: 2,
//       pointRadius: 1,
//       pointHitRadius: 10,
//       trendlineLinear: {
//         colorMin: 'black',
//         colorMax: 'black',
//         width: 1,
//       },
//     },
//   ],
// };

export const config = {
  label: '',
  data: [],
  borderColor: 'rgb(0, 130, 158)',
  borderDashOffset: 0.0,
  pointBorderColor: 'rgb(205, 130,1 58)',
  pointBorderWidth: 3,
  pointHoverRadius: 5,
  pointHoverBackgroundColor: 'rgb(0, 0, 0)',
  pointHoverBorderWidth: 2,
  pointRadius: 1,
  pointHitRadius: 10,
  trendlineLinear: {
    colorMin: 'black',
    colorMax: 'black',
    width: 1,
  },
};
